name: Build and Deploy Qt Application

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Qt
      - name: Set up Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.15.2'

      # Install Dependencies
      - name: Install Dependencies
        run: |
          if [[ "$RUNNER_OS" == "Linux" ]]; then
            sudo apt-get update
            sudo apt-get install -y build-essential
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            brew install <your-dependencies>
          elif [[ "$RUNNER_OS" == "Windows" ]]; then
            choco install <your-dependencies> -y
          fi

      # Build Project
      - name: Build Project
        run: |
          mkdir build
          cd build
          qmake ../your_project.pro
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            nmake  # or 'jom' if using
          else
            make
          fi

      # Package Build
      - name: Package Build
        run: |
          cd build
          if [[ "$RUNNER_OS" == "Linux" ]]; then
            zip -r ../QtChessApp_Linux.zip *
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            zip -r ../QtChessApp_macOS.zip *
          elif [[ "$RUNNER_OS" == "Windows" ]]; then
            zip -r ../QtChessApp_Windows.zip *
          fi

      # Upload Artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: QtChessApp-${{ matrix.os }}
          path: |
            QtChessApp_Linux.zip
            QtChessApp_macOS.zip
            QtChessApp_Windows.zip
          retention-days: 30 
